"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/wallet.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./wallet.js').Config} Config
 * @typedef {import('./wallet.js').Safe} Safe
 * @typedef {import('./wallet.js').WalletMode} WalletMode
 * @typedef {import('./wallet.js').Wallet} Wallet
 */
