"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/dashwallet.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./bin/wallet.js').WalletUtxo} WalletUtxo
 * @typedef {import('./bin/wallet.js').WalletUtxoPartial} WalletUtxoPartial
 * @typedef {import('./bin/wallet.js').FsStoreConfig} FsStoreConfig
 * @typedef {import('./bin/wallet.js').DPayWallets} DPayWallets
 * @typedef {import('./bin/wallet.js').DPrivateWallets} DPrivateWallets
 * @typedef {import('./dashwallet.js').MiniUtxo} MiniUtxo
 * @typedef {import('./dashwallet.js').WalletAddress} WalletAddress
 * @typedef {import('./dashwallet.js').WalletWifPartial} WalletWifPartial
 * @typedef {import('./dashwallet.js').WalletWif} WalletWif
 * @typedef {import('./dashwallet.js').Config} Config
 * @typedef {import('./dashwallet.js').DashSightPartial} DashSightPartial
 * @typedef {import('./dashwallet.js').Store} Store
 * @typedef {import('./dashwallet.js').WalletInstance} WalletInstance
 * @typedef {import('./dashwallet.js').SyncOpts} SyncOpts
 * @typedef {import('./dashwallet.js').BefriendOpts} BefriendOpts
 * @typedef {import('./dashwallet.js').FindFriendOpts} FindFriendOpts
 * @typedef {import('./dashwallet.js').Safe} Safe
 * @typedef {import('./dashwallet.js').Preferences} Preferences
 * @typedef {import('./dashwallet.js').Cache} Cache
 * @typedef {import('./dashwallet.js').PrivateWallet} PrivateWallet
 * @typedef {import('./dashwallet.js').WifInfo} WifInfo
 * @typedef {import('./dashwallet.js').PayWallet} PayWallet
 * @typedef {import('./dashwallet.js').NextInfo} NextInfo
 */
